### ISSUE TITLE
Warning: Use of "shift" without parentheses is ambiguous

### ISSUE THREAD

**Issue by bislink** [jhthorsen/mojolicious-plugin-paypal#1]
Hi Jan Henning Thorsenm

I am an intermediate Perl/CPAN user.

While experimenting with your module with 'use diagnostics' pragmata, I got this error:

Command '"./sandbox.cgi"'
failed with return code 0 and error message
Warning: Use of "shift" without parentheses is ambiguous at
	/usr/local/share/perl5/Mojolicious/Plugin/PayPal.pm line 406 (#1)
    (S ambiguous) You wrote a unary operator followed by something that
    looks like a binary operator that could also have been interpreted as a
    term or unary operator.  For instance, if you know that the rand
    function has a default argument of 1.0, and you write
    
        rand + 5;
    
    you may THINK you wrote the same thing as
    
        rand() + 5;
    
    but in actual fact, you got
    
        rand(+5);
    
    So put in parentheses to say what you really mean.
    .

Do you have any idea how to resolve it?

Appreciate your help/input.

Sudheer Murthy.

**Comment by bislink** [comment]
Here is a related/similar issue/problem on StackOverflow.  Not sure if it could be of help.  
http://stackoverflow.com/questions/1583869/why-is-the-use-of-shift-without-parentheses-is-ambiguous-warning-issued-by-p related to this issue

**Comment by jhthorsen** [comment]
Which version of Perl are you using? I'm surprised this haven't shown up when I have been running my tests.

**Comment by jhthorsen** [comment]
I see it here in 5.10: https://travis-ci.org/jhthorsen/mojolicious-plugin-paypal/jobs/45674663

**Comment by jhthorsen** [comment]
Seems to be fixed in the commit above.

Can you verify, or should I just push to CPAN?

**Comment by jhthorsen** [comment]
Closing this with 0.06 on its way to CPAN.
