### ISSUE TITLE
Allowing to override the redirect_url in register_payment

### ISSUE THREAD

**Issue by sgielen** [jhthorsen/mojolicious-plugin-paypal#2]
Because of the following line in PayPal.pm it is not possible to override the `redirect_url` in `register_payment`:

```
  my $redirect_url = Mojo::URL->new($args->{redirect_url} = $c->req->url->to_abs);
```

If this were changed to:

```
  my $redirect_url = Mojo::URL->new($args->{redirect_url} ||= $c->req->url->to_abs);
```

I believe this would be fixed without losing the default :-)

Thanks a lot for your work on this module!

**Comment by jhthorsen** [comment]
Thanks for reporting in!

Could you provide a pull request for this change?

**Comment by jhthorsen** [comment]
I haven't written any tests, but I did push this feature anyways.

I have several payment plugins on CPAN that I want to uniform. Do you want to help me? I just started on https://github.com/jhthorsen/mojolicious-plugin-payment if you're interested. Maybe there's some clumsy parts of this plugin that you want to fix?

**Comment by sgielen** [comment]
For the moment the project I was using the PayPal plugin for is 'on the shelf'. When I get back to it, I'd be happy to help you port some code to the Payment plugin or improve it where useful :) Thanks for fixing this bug and pushing a release!
